# Generated by Django 5.2 on 2025-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nasciemento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('profissao', models.CharField(max_length=100)),
            ],
        ),
    ]
